name: Sync from Hugging Face

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper syncing

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add Hugging Face remote
        run: |
          git remote add hf https://huggingface.co/spaces/evangelosmeklis/deepdrone
          git fetch hf

      - name: Sync from Hugging Face
        run: |
          # Get the latest commit from Hugging Face
          HF_LATEST=$(git rev-parse hf/main)
          GH_LATEST=$(git rev-parse origin/main)
          
          if [ "$HF_LATEST" != "$GH_LATEST" ]; then
            echo "New changes detected in Hugging Face repository"
            git reset --hard hf/main
            git push origin main
          else
            echo "No new changes to sync"
          fi