name: Sync from Hugging Face
on:
  schedule:
    - cron: "0 * * * *"  # Run every hour
  workflow_dispatch:  # Allow manual triggering
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is important to allow pushing to the repo
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper syncing
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Add Hugging Face remote
        run: |
          git remote add hf https://huggingface.co/spaces/evangelosmeklis/deepdrone
          git fetch hf
      - name: Sync from Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Update remote URL with token for authentication
          git remote set-url hf https://$HF_TOKEN@huggingface.co/spaces/evangelosmeklis/deepdrone
          git fetch hf
          # Get the latest commit from Hugging Face
          HF_LATEST=$(git rev-parse hf/main)
          GH_LATEST=$(git rev-parse origin/main)
          if [ "$HF_LATEST" != "$GH_LATEST" ]; then
            echo "New changes detected in Hugging Face repository"
            git reset --hard hf/main
            git push --force https://x-access-token:${GH_TOKEN}@github.com/evangelosmeklis/deepdrone.git main
          else
            echo "No new changes to sync"
          fi
